# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Check Labels

on:
  pull_request:
    types: [opened, reopened, edited, labeled, unlabeled, synchronize]

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  label-backport-prs:
    permissions:
      contents: read
      pull-requests: read
      issues: write

    name: Label Backport PRs
    if: (github.repository_owner == 'PowerShell' || github.repository_owner == 'TravisEz13')  && github.event.action == 'opened' && startsWith(github.event.pull_request.base.ref, 'release/v') && startsWith(github.event.pull_request.title, '[release/v')
    runs-on: ubuntu-latest

    steps:
    - name: Label Original PRs if backport PR
      continue-on-error: true
      uses: actions/github-script@v7
      with:
        script: |
          const description = github.event.pull_request.body || '';
          const branch = github.event.pull_request.base.ref;
          const match = description.match(/\$\$\$originalprnumber:(\d+)\$\$\$/);
          if (match) {
            const originalPrNumber = match[1];
            console.log(`Original PR number found: ${originalPrNumber}`);

            const labelName = branch.replace('release/v', 'backport-') + '.x-migrated';
            console.log(`labelName: ${labelName}`);

            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: originalPrNumber,
              labels: [labelName]
            });
          } else {
            console.log("No original PR number found in the description.");
          }
          
  test-conditions:
    permissions:
      contents: read

    name: test conditions
    if: (github.repository_owner == 'PowerShell' || github.repository_owner == 'TravisEz13')  
    runs-on: ubuntu-latest

    steps:
    - name: If Opened
      continue-on-error: true
      if: github.event.action == 'opened'
      run: echo "yes"
      
    - name: If ref starts with
      continue-on-error: true
      if: startsWith(github.event.pull_request.base.ref, 'release/v')
      run: echo "yes"
      
    - name: If title starts with
      continue-on-error: true
      if: startsWith(github.event.pull_request.title, '[release/v') }}
      run: echo "yes"      
      
  verify-labels:
    name: Verify Change Log Labels
    if: github.repository_owner == 'PowerShell'
    runs-on: ubuntu-latest

    steps:
    - name: Verify PR has label starting with 'cl-'
      id: verify-labels
      uses: actions/github-script@v7
      with:
        script: |
          const labels = context.payload.pull_request.labels.map(label => label.name.toLowerCase());
          if (!labels.some(label => label.startsWith('cl-'))) {
            core.setFailed("Every PR must have at least one label starting with 'cl-'.");


